# Generated by Django 4.1.7 on 2023-03-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_store_name'),
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mobile')),
            ],
        ),
    ]
