# Generated by Django 4.1.7 on 2023-04-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_store_name'),
        ('customer', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_mobile', to='store.mobile'),
        ),
    ]
