# Generated by Django 4.1.7 on 2023-04-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_store_name'),
        ('customer', '0010_remove_order_mobile_order_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.ManyToManyField(blank=True, to='store.mobile'),
        ),
    ]
