# Generated by Django 4.1.7 on 2023-03-22 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specs', models.TextField()),
                ('photo', models.ImageField(upload_to='mobile_photos')),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobiles', models.ManyToManyField(blank=True, to='store.mobile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strusr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
