# Generated by Django 4.1.7 on 2023-03-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeuser',
            name='mobiles',
        ),
        migrations.RemoveField(
            model_name='storeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
        migrations.DeleteModel(
            name='StoreUser',
        ),
    ]
