# Generated by Django 4.1.7 on 2023-03-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review_alter_profile_user_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
